---
- name: Create network
  virt_net:
    command: define
    name: "{{network_name}}"
    xml: "{{lookup('template', 'network.xml.j2')}}"
- name: Make sure network is up
  virt_net:
    state: active
    name: "{{network_name}}"

- name: Set network to autostart
  ansible.builtin.shell: |
     virsh net-autostart "{{network_name}}"