aparavi-baremetal-appagent-1:
  hosts:
    1.2.3.4:
      vm:
        hostname:
          aparavi-appagent-1
        ip_address:
          192.168.202.5/24
        size: 50G
        memory: 8196
        vcpu: 4
        #swapfile size in bytes
        swapfile_size: 17179869184 # 16GB
        run_commands: 'curl -s https://raw.githubusercontent.com/Aparavi-Operations/aparavi-infrastructure/main/install.sh | sudo bash -s -- -c "client_name" -o "parent_object_id"'

aparavi-baremetal-monitoring:
  hosts:
    1.2.3.5:
      vm:
        hostname:
          aparavi-monitoring
        ip_address:
          192.168.202.6/24
        size: 150G
        memory: 8196
        vcpu: 4
        #swapfile size in bytes
        swapfile_size: 17179869184 # 16GB
        run_commands: 'curl -s https://raw.githubusercontent.com/Aparavi-Operations/aparavi-cloud-receipts/main/kvm/ansible/install_apps/install_monitoring.sh | sudo bash -s --'