---
- name: Install aparavi-appagent-1
  hosts: aparavi-baremetal-appagent-1
  become: true
  pre_tasks:
    - name: Load the vm template
      include_vars: debian_vm_template.yml
    - name: display qemu_img
      debug:
        msg: 
          - "qemu_img: {{ qemu_img }}"
  roles:
    - qemu_img
    - cloud_localds
    - virt_install_vm

- name: Install aparavi-monitoring
  hosts: aparavi-baremetal-monitoring
  become: true
  pre_tasks:
    - name: Load the vm template
      include_vars: debian_vm_template.yml
    - name: display qemu_img
      debug:
        msg: 
          - "qemu_img: {{ qemu_img }}"
  roles:
    - qemu_img
    - cloud_localds
    - virt_install_vm