- name: Create firewall rules for appagent-1
  hosts: aparavi-baremetal-appagent-1
  become: yes 
  roles:
    - set_iptables

- name: Create firewall rules for monitoring
  hosts: aparavi-baremetal-monitoring
  become: yes 
  roles:
    - set_iptables
