{
 "title": "Aparavi overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(node_uname_info, env)"
    }
   },
   {
    "name": "component",
    "label": "Component",
    "query": {
     "query": "label_values(node_uname_info{env=\"$env\"}, component)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Component status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{env=\"$env\",component=~\"$component\"} OR on() vector(0)",
     "legendFormat": "{{ component }}"
    }
   ]
  },
  { "title": "$component", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "component" },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{env=\"$env\",component=\"$component\",mode=\"system\"}[5m])) * 100",
     "legendFormat": "System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{env=\"$env\",component=\"$component\",mode=\"system\"}[5m])) * 100",
     "legendFormat": "User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',component=\"aggregator\"}[5m])) * 100",
     "legendFormat": "Iowait"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{env=\"$env\",component=\"$component\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{env=\"$env\",component=\"$component\"} - node_memory_MemFree_bytes{env=\"$env\",component=\"$component\"} - (node_memory_Cached_bytes{env=\"$env\",component=\"$component\"} + node_memory_Buffers_bytes{env=\"$env\",component=\"$component\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{env=\"$env\",component=\"$component\"} + node_memory_Buffers_bytes{env=\"$env\",component=\"$component\"}",
     "legendFormat": "RAM Cache + Buffer"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{env=\"$env\",component=\"$component\",device!=\"lo\"}[5m])",
     "legendFormat": "RECV {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{env=\"$env\",component=\"$component\",device!=\"lo\"}[5m])",
     "legendFormat": "TRANS {{device}} "
    }
   ]
  }
 ]
}