aparavi-baremetal-hosts:
  hosts:
    158.175.71.44:
    158.175.71.34:
  vars:
    network_name: "br0"
    network_bridge: "br0"
    network_gateway_ip: "192.168.202.1"
    network_dhcp_start: "192.168.202.2"
    network_dhcp_end: "192.168.202.100"