---
- name: Preparations
  hosts: all
  become: true
  tasks:
    - name: Install all the things with apt
      apt:
        update_cache: yes
        name:
          - libvirt-daemon
          - libvirt-daemon-system
          - libvirt-clients
          - python3-libvirt
          - python3-pip
        state: present
    - name: Install some with pip3
      pip:
        name: lxml
    - name: Make sure a libvirtd unit is running
      ansible.builtin.systemd:
        state: started
        name: libvirtd
        enabled: yes
    - name: Make sure a apache2 unit is not running
      ansible.builtin.systemd:
        state: stopped
        name: apache2
        enabled: no
    # - name: Make sure a bind9 unit is not running
    #   ansible.builtin.systemd:
    #     state: stopped
    #     name: bind9
    #     enabled: no
- name: Create network
  hosts: all
  become: true
  roles:
    - libvirt_network

